#!/usr/bin/env python3
"""CI gate: no schema's mutation score may fall.

`tools/schema-mutation.py` mutates each corpus schema one small change at a time and
asks whether any of its vectors notices; its score is killed / (killed + survived). A
high `score_schema.py` tier says a schema agrees with its own vectors, and this says how
much of the schema those vectors actually pin. The harness is deterministic (same
schema, same vectors, same mutants), so this gate compares exactly.

Ratchet against the committed `tools/mutation-baseline.json`, in the same spirit as
`score-baseline.json` and the language floors. Fails when:

  * a baselined schema's score is below its baseline (a vector removed, or a schema
    change no vector checks);
  * a baselined schema no longer has decode vectors, or disappeared (refresh the
    baseline deliberately if that was intended);
  * a schema absent from the baseline scores below --min-score (default 0.80). A new
    schema should arrive with vectors that pin it. 0.80 is met by 142 of the 150
    scored schemas in the corpus the baseline was built from (median 0.98), so it
    asks for coverage typical of the corpus without demanding perfection on day one;
  * a schema has more vectors failing on the UNMUTATED schema than its baseline (a
    new schema: any) - a failing vector kills nothing, so its score would flatter it;
  * the harness reports an error for a schema.

  * a baselined schema's killed count falls by more than its generated mutant count
    does. Removing vectors can RAISE the score, because a mutant only they reached
    becomes `unreached` and leaves the denominator; the killed ratchet catches that.
    A fall matched by the schema offering fewer mutants (a field removed) is reported,
    not failed.

Improvements are reported and locked in by --update.

    python3 tools/mutation-gate.py
    python3 tools/mutation-gate.py --changed-since origin/master   # + survivors
    python3 tools/mutation-gate.py --update

`schemas/devices/_library-composed/` is excluded by default. Those files are generated by
`tools/compose_library_vectors.py`, one standalone schema per library vector, so their
score measures one example of a definition catalogue rather than a device, and a PR
author cannot raise it by editing the file - it is regenerated wholesale. Its vectors
come from `schemas/library/`. Pass --include-library-composed to score them anyway.
"""

import argparse
import importlib.util
import json
import multiprocessing
import os
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS = REPO_ROOT / "tools"
CORPUS = REPO_ROOT / "schemas" / "devices"
BASELINE_FILE = TOOLS / "mutation-baseline.json"

DEFAULT_MIN_SCORE = 0.80
LIBRARY_COMPOSED = "_library-composed"
#: The harness rounds scores to 4 places; this only absorbs float representation.
EPSILON = 1e-9


def load_harness():
    path = TOOLS / "schema-mutation.py"
    spec = importlib.util.spec_from_file_location("schema_mutation", str(path))
    module = importlib.util.module_from_spec(spec)
    sys.modules["schema_mutation"] = module
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------------------- rules


def compare(
    baseline: Dict[str, Dict[str, Any]],
    current: Dict[str, Dict[str, Any]],
    min_score: float = DEFAULT_MIN_SCORE,
) -> Dict[str, List[str]]:
    """Apply the ratchet. Maps are {schema_key: {score, killed, survived, ...}}.

    Returns lists of `regressions`, `improvements` and `notes`. Pure: no I/O.
    """
    regressions = []  # type: List[str]
    improvements = []  # type: List[str]
    notes = []  # type: List[str]

    for key in sorted(set(baseline) - set(current)):
        regressions.append(
            "%s: in the baseline but not scored now - it lost its decode vectors or "
            "was removed; refresh the baseline with --update if deliberate" % key
        )
    for key in sorted(current):
        now = current[key]
        if now.get("error"):
            regressions.append("%s: harness error: %s" % (key, now["error"]))
            continue
        score = now.get("score")
        was = baseline.get(key)
        if was is None:
            if now.get("failing_original", 0):
                regressions.append(
                    "%s: new schema has %d vector(s) failing on the unmutated schema"
                    % (key, now["failing_original"])
                )
            if score is None:
                notes.append("%s: new schema, no scorable mutants" % key)
            elif score + EPSILON < min_score:
                regressions.append(
                    "%s: new schema scores %s, below the %s floor for new schemas "
                    "(killed %d, survived %d) - add vectors that pin the survivors"
                    % (
                        key,
                        _pct(score),
                        _pct(min_score),
                        now["killed"],
                        now["survived"],
                    )
                )
            else:
                improvements.append(
                    "%s: new schema, %s (killed %d)" % (key, _pct(score), now["killed"])
                )
            continue
        old = was.get("score")
        if old is not None and score is None:
            regressions.append(
                "%s: scored %s in the baseline, no scorable mutants now"
                % (key, _pct(old))
            )
            continue
        if old is None or score is None:
            if old is None and score is not None:
                improvements.append("%s: now scored, %s" % (key, _pct(score)))
            continue
        lost = was["killed"] - now["killed"]
        shrink = was.get("generated", 0) - now.get("generated", 0)
        # Fewer vectors can RAISE the score: a mutant only they reached becomes
        # `unreached`, which the score leaves out. So killed is ratcheted too, and a
        # fall is excused only by the schema itself offering fewer mutants.
        coverage_lost = lost > 0 and lost > max(shrink, 0)
        if score + EPSILON < old:
            regressions.append(
                "%s: mutation score fell %s -> %s (killed %d -> %d, survived %d -> %d)"
                % (
                    key,
                    _pct(old),
                    _pct(score),
                    was["killed"],
                    now["killed"],
                    was["survived"],
                    now["survived"],
                )
            )
        elif coverage_lost:
            regressions.append(
                "%s: killed fell %d -> %d while the schema's mutants fell only "
                "%d -> %d - vectors that pinned those sites are gone (score %s -> %s)"
                % (
                    key,
                    was["killed"],
                    now["killed"],
                    was.get("generated", 0),
                    now.get("generated", 0),
                    _pct(old),
                    _pct(score),
                )
            )
        elif score > old + EPSILON:
            improvements.append(
                "%s: mutation score rose %s -> %s" % (key, _pct(old), _pct(score))
            )
        elif lost > 0:
            notes.append(
                "%s: killed fell %d -> %d with the schema's mutants %d -> %d"
                % (
                    key,
                    was["killed"],
                    now["killed"],
                    was.get("generated", 0),
                    now.get("generated", 0),
                )
            )
        elif lost < 0:
            improvements.append(
                "%s: killed rose %d -> %d" % (key, was["killed"], now["killed"])
            )
        failing, was_failing = now.get("failing_original", 0), was.get(
            "failing_original", 0
        )
        if failing > was_failing:
            regressions.append(
                "%s: %d vector(s) now fail on the unmutated schema (baseline %d); a "
                "failing vector kills nothing, so the score above overstates it"
                % (key, failing, was_failing)
            )
    return {"regressions": regressions, "improvements": improvements, "notes": notes}


def _pct(value):
    return "n/a" if value is None else "%.1f%%" % (value * 100)


def distribution(entries: Dict[str, Dict[str, Any]]) -> Dict[str, int]:
    bands = [
        ("100%", 1.0, 1.01),
        ("95-99%", 0.95, 1.0),
        ("90-94%", 0.90, 0.95),
        ("80-89%", 0.80, 0.90),
        ("70-79%", 0.70, 0.80),
        ("<70%", -1.0, 0.70),
    ]
    out = {label: 0 for label, _lo, _hi in bands}
    out["unscored"] = 0
    for entry in entries.values():
        score = entry.get("score")
        if score is None:
            out["unscored"] += 1
            continue
        for label, lo, hi in bands:
            if lo <= score < hi:
                out[label] += 1
                break
    return out


# --------------------------------------------------------------------------- running


def _key(path: Path, schemas_dir: Path) -> str:
    return path.resolve().relative_to(schemas_dir.resolve()).as_posix()


def select_files(harness, schemas_dir: Path, include_library: bool) -> List[Path]:
    files = harness.schema_files([str(schemas_dir)])
    if not include_library:
        files = [
            f
            for f in files
            if _key(f, schemas_dir).split("/", 1)[0] != LIBRARY_COMPOSED
        ]
    return files


def run_harness(
    schemas_dir: Path, include_library: bool = False, workers: int = 1
) -> Dict[str, Dict[str, Any]]:
    """{schema_key: full harness report} for every scorable schema under the tree."""
    harness = load_harness()
    files = select_files(harness, schemas_dir, include_library)
    jobs = [(str(f), None, 5.0) for f in files]
    jobs.sort(key=lambda j: -os.path.getsize(j[0]))
    # fork, so the workers inherit the harness module loaded above; a platform
    # without it runs serially rather than failing to unpickle the job function.
    fork = "fork" in multiprocessing.get_all_start_methods()
    if workers > 1 and len(jobs) > 1 and fork:
        context = multiprocessing.get_context("fork")
        with ProcessPoolExecutor(max_workers=workers, mp_context=context) as pool:
            reports = list(pool.map(harness.mutate_file, jobs))
    else:
        reports = [harness.mutate_file(j) for j in jobs]
    return {_key(Path(job[0]), schemas_dir): r for job, r in zip(jobs, reports)}


def slim(report: Dict[str, Any]) -> Dict[str, Any]:
    if "error" in report:
        return {"error": report["error"]}
    return {
        "score": report["score"],
        "killed": report["killed"],
        "survived": report["survived"],
        "unreached": report["unreached"],
        "generated": report["generated"],
        "vectors": report["vectors"],
        "provenance": report["provenance"],
        "failing_original": len(report.get("vectors_failing_original") or []),
    }


def build_baseline(current, min_score, include_library) -> Dict[str, Any]:
    entries = {k: slim(v) for k, v in sorted(current.items())}
    return {
        "about": (
            "Committed ratchet for tools/mutation-gate.py: each schema's "
            "tools/schema-mutation.py score may not fall. Regenerate only "
            "deliberately (--update) and say why in the commit message."
        ),
        "min_score_new": min_score,
        "include_library_composed": include_library,
        "distribution": distribution(entries),
        "schemas": entries,
    }


def changed_schemas(ref: str, schemas_dir: Path) -> List[str]:
    """Schema keys changed since `ref`, including uncommitted and untracked files."""
    names = set()
    for cmd in (
        ["git", "diff", "--name-only", ref, "--"],
        ["git", "ls-files", "--others", "--exclude-standard"],
    ):
        out = subprocess.run(
            cmd, cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=60
        )
        if out.returncode != 0:
            raise SystemExit("git failed: %s\n%s" % (" ".join(cmd), out.stderr))
        names.update(line.strip() for line in out.stdout.splitlines() if line.strip())
    keys = []
    root = schemas_dir.resolve()
    for name in sorted(names):
        path = (REPO_ROOT / name).resolve()
        if path.suffix == ".yaml":
            try:
                keys.append(path.relative_to(root).as_posix())
            except ValueError:
                continue
    return keys


def print_survivors(key: str, report: Dict[str, Any]):
    survivors = report.get("survivors") or []
    print(
        "\n%s: %s, %d surviving mutant(s)"
        % (key, _pct(report.get("score")), len(survivors))
    )
    for s in survivors:
        extra = ""
        if s.get("changed_keys"):
            extra = "  (changed: %s)" % ", ".join(s["changed_keys"])
        print(
            "    %-10s %-40s %s [%s]%s"
            % (s["operator"], s["field"], s["detail"], s.get("kind", ""), extra)
        )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--schemas-dir", default=str(CORPUS))
    parser.add_argument("--baseline", default=str(BASELINE_FILE))
    parser.add_argument(
        "--min-score",
        type=float,
        default=None,
        help="floor for schemas not in the baseline (default: the baseline's "
        "min_score_new, else %.2f)" % DEFAULT_MIN_SCORE,
    )
    parser.add_argument("--include-library-composed", action="store_true")
    parser.add_argument("--workers", type=int, default=os.cpu_count() or 1)
    parser.add_argument(
        "--changed-since",
        metavar="REF",
        help="list surviving mutants of every schema changed since this git ref",
    )
    parser.add_argument(
        "--update", action="store_true", help="rewrite the baseline from this run"
    )
    args = parser.parse_args(argv)

    schemas_dir = Path(args.schemas_dir).resolve()
    baseline_path = Path(args.baseline)
    baseline = (
        json.loads(baseline_path.read_text(encoding="utf-8"))
        if baseline_path.exists()
        else None
    )
    min_score = args.min_score
    if min_score is None:
        min_score = (baseline or {}).get("min_score_new", DEFAULT_MIN_SCORE)

    started = time.time()
    current = run_harness(schemas_dir, args.include_library_composed, args.workers)
    elapsed = time.time() - started
    slimmed = {k: slim(v) for k, v in current.items()}
    dist = distribution(slimmed)
    print(
        "%d schemas scored in %.1fs: %s"
        % (len(current), elapsed, ", ".join("%s %d" % kv for kv in dist.items()))
    )

    if args.changed_since:
        keys = changed_schemas(args.changed_since, schemas_dir)
        shown = [k for k in keys if k in current]
        print(
            "\nSchemas changed since %s: %d (%d scored)"
            % (args.changed_since, len(keys), len(shown))
        )
        for key in shown:
            print_survivors(key, current[key])
        print()

    if args.update:
        data = build_baseline(current, min_score, args.include_library_composed)
        baseline_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print("wrote %s" % baseline_path)
        return 0
    if baseline is None:
        print("FAIL: no baseline at %s; create one with --update" % baseline_path)
        return 1
    if bool(baseline.get("include_library_composed")) != args.include_library_composed:
        print(
            "FAIL: the baseline was built with include_library_composed=%s; run with "
            "the same setting" % baseline.get("include_library_composed")
        )
        return 1

    outcome = compare(baseline.get("schemas", {}), slimmed, min_score)
    for line in outcome["improvements"]:
        print("IMPROVED: %s" % line)
    for line in outcome["notes"]:
        print("NOTE: %s" % line)
    if outcome["improvements"]:
        print(
            "%d improvement(s) not yet locked in - refresh the baseline with "
            "--update" % len(outcome["improvements"])
        )
    for line in outcome["regressions"]:
        print("REGRESSION: %s" % line)
    if outcome["regressions"]:
        failed = sorted(set(r.split(":", 1)[0] for r in outcome["regressions"]))
        for key in failed:
            if key in current and not args.changed_since:
                print_survivors(key, current[key])
        print("FAIL: %d mutation-score regression(s)" % len(outcome["regressions"]))
        return 1
    print("PASS: no mutation-score regressions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
