#!/usr/bin/env python3
"""provenance-gate.py - independent provenance for the device schemas a change touches.

A test vector recorded from our own decoder proves nothing: it locks in whatever the
decoder did, bugs included (AGENTS.md, "Test vectors must come from outside our own
decoder"). PS-264 caps a schema with no independently sourced vector at Silver; this
gate applies the same rule at review time, to the schemas a change adds or modifies:

  FAIL  a changed device schema has no vector whose `source:` is independent
        (vendor-doc, vendor-codec, field-capture, spec-example);
  FAIL  a vector added by the change declares no `source:` (or an unknown one);
  FAIL  a changed `_language-conformance/` fixture has a vector declaring no source.
        Fixtures may be `source: generated` - they pin a construct, not a device -
        but they must say so;
  WARN  a vector kept its name, stimulus (payload / input / port) and source while its
        expected outcome changed. That is what re-recording a vector from our own
        decoder looks like; it may be a legitimate correction, so a human decides.

`_library-composed/` is generated by tools/compose_library_vectors.py and is skipped;
its provenance is set in `schemas/library/`.

Usage:
    python3 tools/provenance-gate.py                    # vs origin/master
    python3 tools/provenance-gate.py --base main --include-worktree
    python3 tools/provenance-gate.py --all              # corpus-wide status, never fails
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

DEVICES = "schemas/devices/"
FIXTURES = DEVICES + "_language-conformance/"
GENERATED = DEVICES + "_library-composed/"

INDEPENDENT_SOURCES = frozenset(
    {"vendor-doc", "vendor-codec", "field-capture", "spec-example"}
)
KNOWN_SOURCES = INDEPENDENT_SOURCES | {"generated"}

#: What a vector is asked, and what it claims the answer is.
STIMULUS_KEYS = ("payload", "fPort", "fport", "port", "input", "input_metadata")
OUTCOME_KEYS = ("expected", "expected_payload", "expected_warnings")


# --------------------------------------------------------------------------------------
# git
# --------------------------------------------------------------------------------------


def _git(repo: Path, *args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git"] + list(args),
        cwd=str(repo),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    if check and proc.returncode != 0:
        raise RuntimeError("git %s: %s" % (" ".join(args), proc.stderr.strip()))
    return proc.stdout


def _show(repo: Path, rev: str, path: str) -> Optional[str]:
    proc = subprocess.run(
        ["git", "show", "%s:%s" % (rev, path)],
        cwd=str(repo),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    return proc.stdout if proc.returncode == 0 else None


def _is_schema_path(path: str) -> bool:
    return path.startswith(DEVICES) and path.endswith((".yaml", ".yml"))


def changed_schemas(
    repo: Path, base: str, include_worktree: bool
) -> List[Tuple[str, Optional[str]]]:
    """(new path, path at the merge base or None) for every added/modified schema."""
    out: Dict[str, Optional[str]] = {}
    status = _git(repo, "diff", "--name-status", "-M", "%s...HEAD" % base)
    lines = status.splitlines()
    if include_worktree:
        lines += _git(repo, "diff", "--name-status", "-M", "HEAD").splitlines()
        lines += [
            "A\t" + p
            for p in _git(repo, "ls-files", "--others", "--exclude-standard").split()
        ]
    for line in lines:
        parts = line.split("\t")
        if not parts or not parts[0]:
            continue
        code = parts[0][0]
        if code == "D":
            out.pop(parts[1], None)
            continue
        if code == "R" and len(parts) == 3:
            old, new = parts[1], parts[2]
        elif code in "AMCT" and len(parts) >= 2:
            old, new = parts[-1], parts[-1]
        else:
            continue
        if _is_schema_path(new):
            # The first (committed) entry wins: its old path is the base's.
            out.setdefault(new, old)
    return sorted(out.items())


# --------------------------------------------------------------------------------------
# Vectors
# --------------------------------------------------------------------------------------


def _vectors(schema: Any) -> List[dict]:
    if not isinstance(schema, dict):
        return []
    return [v for v in schema.get("test_vectors") or [] if isinstance(v, dict)]


def _identity(vector: dict, index: int) -> str:
    name = vector.get("name")
    if name:
        return str(name)
    return "#%d:%s" % (index, json.dumps(_part(vector, STIMULUS_KEYS), sort_keys=True))


def _part(vector: dict, keys: Tuple[str, ...]) -> Dict[str, Any]:
    return {k: vector[k] for k in keys if k in vector}


def _canon(value: Any) -> str:
    return json.dumps(value, sort_keys=True, default=str)


def _source(vector: dict) -> Optional[str]:
    src = vector.get("source")
    return str(src) if src is not None else None


class Report:
    def __init__(self, path: str):
        self.path = path
        self.failures: List[str] = []
        self.warnings: List[str] = []
        self.notes: List[str] = []

    @property
    def status(self) -> str:
        if self.failures:
            return "FAIL"
        if self.warnings:
            return "WARN"
        return "PASS"


def check_schema(path: str, new_text: str, old_text: Optional[str]) -> Report:
    report = Report(path)
    try:
        new = yaml.safe_load(new_text) or {}
    except yaml.YAMLError as exc:
        report.failures.append("does not parse: %s" % str(exc).splitlines()[0])
        return report
    try:
        old = yaml.safe_load(old_text) if old_text is not None else None
    except yaml.YAMLError:
        old = None

    vectors = _vectors(new)
    old_vectors = {
        _identity(v, i): v for i, v in enumerate(_vectors(old) if old else [])
    }
    fixture = path.startswith(FIXTURES)
    independent = [v for v in vectors if _source(v) in INDEPENDENT_SOURCES]

    report.notes.append(
        "%d vector(s), %d independent%s"
        % (len(vectors), len(independent), "" if old_text is not None else ", new file")
    )

    for i, vector in enumerate(vectors):
        ident = _identity(vector, i)
        src = _source(vector)
        added = ident not in old_vectors
        if src is not None and src not in KNOWN_SOURCES:
            report.failures.append(
                "vector %r: unknown source %r (one of: %s)"
                % (ident, src, ", ".join(sorted(KNOWN_SOURCES)))
            )
        elif src is None and (fixture or added):
            if fixture:
                report.failures.append(
                    "vector %r declares no source: a fixture may be `generated`, "
                    "but must say so" % ident
                )
            else:
                report.failures.append(
                    "vector %r was added without a `source:` - say where its expected "
                    "values came from (PS-263)" % ident
                )
        if not added:
            before = old_vectors[ident]
            same_stimulus = _canon(_part(before, STIMULUS_KEYS)) == _canon(
                _part(vector, STIMULUS_KEYS)
            )
            same_outcome = _canon(_part(before, OUTCOME_KEYS)) == _canon(
                _part(vector, OUTCOME_KEYS)
            )
            if same_stimulus and not same_outcome and _source(before) == src:
                report.warnings.append(
                    "vector %r: expected values changed while its payload and source "
                    "(%s) did not - if they were re-recorded from our own decoder, "
                    "that is `source: generated`, and the old values may have been "
                    "right" % (ident, src or "none")
                )

    if not fixture and not independent:
        if not vectors:
            report.failures.append(
                "no test vectors: a schema with none cannot be verified at all"
            )
        else:
            report.failures.append(
                "no vector has an independent source (%s); PS-264 caps it at Silver. "
                "Take vectors from the vendor's documentation or codec, not our output"
                % ", ".join(sorted(INDEPENDENT_SOURCES))
            )
    return report


def print_report(report: Report) -> None:
    print("%-4s %s  (%s)" % (report.status, report.path, "; ".join(report.notes)))
    for msg in report.failures:
        print("       FAIL  " + msg)
    for msg in report.warnings:
        print("       WARN  " + msg)


def run_diff(repo: Path, base: str, include_worktree: bool) -> int:
    try:
        merge_base = _git(repo, "merge-base", base, "HEAD").strip()
    except RuntimeError as exc:
        print(
            "provenance-gate: cannot resolve base %r: %s" % (base, exc), file=sys.stderr
        )
        return 2
    changes = changed_schemas(repo, base, include_worktree)
    reports = []
    skipped = []
    for new_path, old_path in changes:
        if new_path.startswith(GENERATED):
            skipped.append(new_path)
            continue
        if include_worktree:
            disk = repo / new_path
            if not disk.exists():
                continue
            new_text = disk.read_text(encoding="utf-8")
        else:
            new_text = _show(repo, "HEAD", new_path)
            if new_text is None:
                continue
        old_text = _show(repo, merge_base, old_path) if old_path else None
        reports.append(check_schema(new_path, new_text, old_text))

    print(
        "Provenance gate: %d changed schema(s) vs %s (merge base %s)%s"
        % (
            len(reports),
            base,
            merge_base[:10],
            " + worktree" if include_worktree else "",
        )
    )
    for report in reports:
        print_report(report)
    if skipped:
        print("skipped %d generated schema(s) in %s" % (len(skipped), GENERATED))
    failed = [r for r in reports if r.status == "FAIL"]
    warned = [r for r in reports if r.status == "WARN"]
    print(
        "\n%d failed, %d warned, %d passed"
        % (len(failed), len(warned), len(reports) - len(failed) - len(warned))
    )
    return 1 if failed else 0


# --------------------------------------------------------------------------------------
# --all: corpus-wide status, for visibility only
# --------------------------------------------------------------------------------------


def run_all(repo: Path) -> int:
    root = repo / DEVICES
    by_family: Dict[str, Dict[str, int]] = {}
    no_vectors: List[str] = []
    no_independent: List[str] = []
    fixtures_unsourced: List[str] = []
    total_schemas = 0
    for path in sorted(root.rglob("*.yaml")):
        rel = path.relative_to(repo).as_posix()
        if rel.startswith(GENERATED):
            continue
        schema = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        vectors = _vectors(schema)
        family = rel[len(DEVICES) :].split("/", 1)[0]
        stats = by_family.setdefault(
            family, {"schemas": 0, "vectors": 0, "unsourced": 0, "independent": 0}
        )
        stats["schemas"] += 1
        stats["vectors"] += len(vectors)
        unsourced = [v for v in vectors if _source(v) is None]
        stats["unsourced"] += len(unsourced)
        stats["independent"] += sum(
            1 for v in vectors if _source(v) in INDEPENDENT_SOURCES
        )
        if rel.startswith(FIXTURES):
            fixtures_unsourced.extend(
                "%s::%s" % (rel, v.get("name")) for v in unsourced
            )
            continue
        total_schemas += 1
        if not vectors:
            no_vectors.append(rel)
        elif not any(_source(v) in INDEPENDENT_SOURCES for v in vectors):
            no_independent.append(rel)

    print("Corpus provenance (device schemas; %s excluded)" % GENERATED)
    print("-" * 66)
    print(
        "%-24s %8s %8s %12s %10s"
        % ("family", "schemas", "vectors", "independent", "no source")
    )
    for family, s in sorted(by_family.items()):
        print(
            "%-24s %8d %8d %12d %10d"
            % (family, s["schemas"], s["vectors"], s["independent"], s["unsourced"])
        )
    unsourced_total = sum(
        s["unsourced"] for f, s in by_family.items() if f != "_language-conformance"
    )
    print("-" * 66)
    print("%d device schemas (fixtures excluded)" % total_schemas)
    print("  %d have no test vectors" % len(no_vectors))
    print("  %d have vectors but none independently sourced" % len(no_independent))
    print(
        "  %d pass the gate's schema rule"
        % (total_schemas - len(no_vectors) - len(no_independent))
    )
    print("%d device vectors declare no source at all" % unsourced_total)
    print("%d fixture vectors declare no source" % len(fixtures_unsourced))
    if no_independent:
        print("\nVectors, but nothing independent:")
        for rel in no_independent:
            print("  " + rel)
    for item in fixtures_unsourced:
        print("  fixture without source: " + item)
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--base", default="origin/master", help="ref to diff against (REF...HEAD)"
    )
    parser.add_argument(
        "--include-worktree",
        action="store_true",
        help="also check uncommitted and untracked changes",
    )
    parser.add_argument(
        "--all", action="store_true", help="report corpus-wide status; never fails"
    )
    parser.add_argument(
        "--repo", default=str(REPO_ROOT), help="repository root (default: this one)"
    )
    args = parser.parse_args(argv)
    repo = Path(args.repo).resolve()
    if args.all:
        return run_all(repo)
    return run_diff(repo, args.base, args.include_worktree)


if __name__ == "__main__":
    sys.exit(main())
